/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/global/Button/BaseButton.vue')['default']
    BaseIconMdiClose: typeof import('~icons/mdi/close')['default']
    BaseIconMdiConsole: typeof import('~icons/mdi/console')['default']
    BaseIconMdiHome: typeof import('~icons/mdi/home')['default']
    BaseIconMdiMenu: typeof import('~icons/mdi/menu')['default']
    BaseIconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    BaseIconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    BaseSwitch: typeof import('./src/components/global/Switch/BaseSwitch.vue')['default']
    BaseTitle: typeof import('./src/components/global/Title/BaseTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/Footer/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/Header/TheHeader.vue')['default']
    ThemeSwitch: typeof import('./src/components/Header/components/ThemeSwitch.vue')['default']
  }
}
