/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: (typeof import('./src/components/global/Button/BaseButton.vue'))['default'];
    BaseSwitch: (typeof import('./src/components/global/Switch/BaseSwitch.vue'))['default'];
    BaseTitle: (typeof import('./src/components/global/Title/BaseTitle.vue'))['default'];
    HeaderLogo: (typeof import('./src/components/Header/components/HeaderLogo.vue'))['default'];
    HeaderMenuButton: (typeof import('./src/components/Header/components/HeaderMenuButton.vue'))['default'];
    HeaderNavBar: (typeof import('./src/components/Header/components/HeaderNavBar.vue'))['default'];
    HeaderNavBarItem: (typeof import('./src/components/Header/components/HeaderNavBarItem.vue'))['default'];
    HeaderOpenCloseMenu: (typeof import('./src/components/Header/components/HeaderOpenCloseMenu.vue'))['default'];
    HeaderSkeleton: (typeof import('./src/components/Header/components/HeaderSkeleton.vue'))['default'];
    HeaderTitle: (typeof import('./src/components/Header/components/HeaderTitle.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    TheFooter: (typeof import('./src/components/Footer/TheFooter.vue'))['default'];
    TheHeader: (typeof import('./src/components/Header/TheHeader.vue'))['default'];
    ThemeSwitch: (typeof import('./src/components/Header/components/ThemeSwitch.vue'))['default'];
  }
}
