name: Commit Lint

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Lint Commit Message
        run: npm run commitlint
