name: Vue CI

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Project Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Bump version and generate changelog
        run: |
          npm run release
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md package.json
          git commit -m "chore(release): bump version"
          git push

      - name: GitHub Status Check
        run: echo "All steps have passed!"
